Repository AngleSharp/AngleSharp, pull requests merged in 2021-04, with the labels that each got.

#945 Remove duplicate PackageReferences from test project
  src/AngleSharp.Core.Tests/AngleSharp.Core.Tests.csproj
Labels: tool-chain

#947 Text source optimization
  src/AngleSharp/Text/TextSource.cs
Labels: enhancement, parser, performance

#951 Replace ForEachRange with one-time loops
  src/AngleSharp/Dom/DocumentExtensions.cs
  src/AngleSharp/Dom/Internal/CharacterData.cs
  src/AngleSharp/Dom/Internal/Node.cs
  src/AngleSharp/Dom/Internal/TextNode.cs
Labels: dom, enhancement, performance

#953 Remove reflection use in DefaultHttpRequester
  src/AngleSharp/Css/Parser/CssSelectorConstructor.cs
  src/AngleSharp/Io/DefaultHttpRequester.cs
  src/AngleSharp/Io/RequesterExtensions.cs
Labels: enhancement, requester

#957 Add ConfigureAwaitChecker.Analyzer and fix issues
  src/AngleSharp/AngleSharp.Core.csproj
  src/AngleSharp/Browser/Dom/Events/TrackEvent.cs
  src/AngleSharp/Dom/Internal/Document.cs
  src/AngleSharp/Html/LinkRels/StyleSheetLinkRelation.cs
  src/AngleSharp/Io/BaseRequester.cs
Labels: enhancement, tool-chain

#958 Tidying
  src/AngleSharp/BrowsingContextExtensions.cs
  src/AngleSharp/Css/Parser/CssSelectorConstructor.cs
  src/AngleSharp/Dom/CreateDocumentOptions.cs
  src/AngleSharp/Dom/IShadowRoot.cs
  src/AngleSharp/Dom/Internal/CollectionExtensions.cs
  src/AngleSharp/Dom/Internal/DefaultAttributeObserver.cs
  src/AngleSharp/Dom/Internal/Document.cs
  src/AngleSharp/Dom/Internal/DocumentFragment.cs
  src/AngleSharp/Dom/Internal/DocumentType.cs
  src/AngleSharp/Dom/Internal/Element.cs
  src/AngleSharp/Dom/Internal/HtmlFormControlsCollection.cs
  src/AngleSharp/Dom/Internal/ShadowRoot.cs
  src/AngleSharp/Dom/Internal/Window.cs
  src/AngleSharp/Dom/QueryExtensions.cs
  src/AngleSharp/Html/Dom/Internal/HtmlDataListElement.cs
  src/AngleSharp/Html/Dom/Internal/HtmlElement.cs
  src/AngleSharp/Html/Dom/Internal/HtmlSelectElement.cs
  src/AngleSharp/Html/Dom/Internal/HtmlSlotElement.cs
  src/AngleSharp/Html/Dom/Internal/HtmlTableElement.cs
  src/AngleSharp/Html/FormDataSet.cs
  src/AngleSharp/Html/MinifyMarkupFormatter.cs
  src/AngleSharp/Io/MimeType.cs
Labels: enhancement

#959 Improve Code Quality
  README.md
  src/AngleSharp/Css/Parser/CssSelectorToken.cs
  src/AngleSharp/Css/Priority.cs
  src/AngleSharp/Dom/EventTarget.cs
  src/AngleSharp/Dom/Internal/NamedNodeMap.cs
  src/AngleSharp/Dom/Internal/NodeEnumerable.cs
  src/AngleSharp/Html/LinkRels/ImportLinkRelation.cs
  src/AngleSharp/Html/Parser/Tokens/HtmlAttributeToken.cs
  src/AngleSharp/Io/MimeType.cs
  src/AngleSharp/Io/Processors/ImageRequestProcessor.cs
  src/AngleSharp/Io/Processors/ResourceRequestProcessor.cs
  src/AngleSharp/Text/StringExtensions.cs
  src/AngleSharp/Text/TextPosition.cs
  src/AngleSharp/Text/TextRange.cs
Labels: enhancement

#961 Update test runtime to netcoreapp3.1
  src/AngleSharp.Core.Tests/AngleSharp.Core.Tests.csproj
Labels: enhancement
