Repository AngleSharp/AngleSharp, pull requests merged in 2024-12, with the labels that each got.

#1213 Fix 1212
  src/AngleSharp.Core.Tests/Library/CookieHandling.cs
  src/AngleSharp/Io/MemoryCookieProvider.cs
Labels: cookie

#1211 Issue 1210 isstepmismatch validation
  src/AngleSharp.Core.Tests/Html/ValidityStepMismatch.cs
  src/AngleSharp/Html/InputTypes/BaseInputType.cs
Labels: enhancement

#1214 Release 1.2.0
  .github/workflows/ci.yml
  .nuke/build.schema.json
  CHANGELOG.md
  CONTRIBUTORS.md
  README.md
  build.cmd
  build.ps1
  build.sh
  docs/general/01-Basics.md
  nuke/Build.cs
  nuke/_build.csproj
  src/AngleSharp.Benchmarks/AngleSharp.Benchmarks.csproj
  src/AngleSharp.Core.Docs/package.json
  src/AngleSharp.Core.Tests/AngleSharp.Core.Tests.csproj
  src/AngleSharp.Core.Tests/Css/StyleExtensions.cs
  src/AngleSharp.Core.Tests/Examples/Questions.cs
  src/AngleSharp.Core.Tests/External/PageRequester.cs
  src/AngleSharp.Core.Tests/Html/DOM.cs
  src/AngleSharp.Core.Tests/Html/ValidityStepMismatch.cs
  src/AngleSharp.Core.Tests/Library/CookieHandling.cs
  src/AngleSharp.Core.Tests/Library/OptimizationPool.cs
  src/AngleSharp.Core.sln
  src/AngleSharp.nuspec
  src/AngleSharp/AngleSharp.Core.csproj
  src/AngleSharp/Dom/ElementExtensions.cs
  src/AngleSharp/Dom/Internal/DefaultAttributeObserver.cs
  src/AngleSharp/Html/Dom/Internal/HtmlLinkElement.cs
  src/AngleSharp/Html/InputTypes/BaseInputType.cs
  src/AngleSharp/Html/Parser/HtmlDomBuilder.cs
  src/AngleSharp/Html/Parser/HtmlParserOptions.cs
  src/AngleSharp/Html/Parser/HtmlTokenizer.cs
  src/AngleSharp/Io/MemoryCookieProvider.cs
  src/AngleSharp/Text/StringBuilderPool.cs
  src/Directory.Build.props
Labels: release
